version: "3"

services:
  proxy:
    image: nginx
    ports:
    - "80:80"
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf 
    restart: unless-stopped

  client:
    build: ./client #to be changed to the image
    restart: unless-stopped

  server:
    build: ./server #to be changed to the image
    environment:
      - DATABASE_URL=mongodb://mongodb:rootpassword@mongodb_container:27017/pet_prodigy?authSource=admin
      - PORT=8080
      - TOKEN_SECRET=10
      - SALT=10 
      - CAT_API_KEY=live_NhhEo1IsVYMG1QcrzTv0dqorIM3NAPiMkjGmNewqB4GQs7v3wSEpgj3toaAPCSbN
    restart: unless-stopped

  mongodb_container:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - /usr/src/db/pet_prodigy:/data/db
    restart: unless-stopped
