version: "18"
services:
  web:
    build: .
    ports:
      - "9999:8080"
    environment:
      - DATABASE_URL=mongodb://mongodb_container/pet_prodigy
      - PORT=8080
      - TOKEN_SECRET=10
      - SALT=10 
      - CAT_API_KEY=live_NhhEo1IsVYMG1QcrzTv0dqorIM3NAPiMkjGmNewqB4GQs7v3wSEpgj3toaAPCSbN

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
