[runtime]
name = "docker"

[[services]]
name = "client"
directory = "client"
dockerfile = "client/Dockerfile"
port = 3000

[[services]]
name = "server"
directory = "server"
dockerfile = "server/Dockerfile"
port = 8080
