GET http://localhost:8000/users

###
GET  http://localhost:8000/users/63d56a907808d15b56b5c599

###
POST http://localhost:8000/users
Content-Type: application/json

{
  "username": "test",
  "password": "123"
}

###
PATCH http://localhost:8000/users/63d56a907808d15b56b5c599
Content-Type: application/json

{
    "username": "John",
    "password": "321"
}

###
DELETE http://localhost:8000/users/63d563abc57c2b859b795d6a
