name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build server
        run: |
         cd ./server
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pet_prodigy_server:latest
      - name: Push server
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pet_prodigy_server:latest


